### ISSUE TITLE
Ways of controlling whether a Buyer is a Contracting Authority or not, and vice-versa.

### ISSUE THREAD

**Issue by lbota** [eProcurement-everis/O3PO#3]
Proposal 1: Use the Buyer and Contracting Authority's identifiers, if they match, they are the same.
Proposal 2: Use the property same as for the individuals.
Proposal 3: Think about other possible solutions and solutions from other ontologies.
Proposal 4: Use SHACL (https://www.w3.org/TR/shacl/)

**Comment by paulakeen** [comment]
sameAs SHOULD be instantiated while loading the triple store repository with individuals.
